<a href="https://colab.research.google.com/github/yunju-1118/ESAA/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.nbytes)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_5 = np.zeros(10)
null_5[4] = 1
print(null_5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
num = np.arange(start=10, stop=50)
print(num)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
num_reverse = np.sort(num)[::-1]
print(num_reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
mat = np.arange(0,9)
mat = mat.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.array([1,2,0,0,4,0])
B = (A != 0)
indices = np.arange(len(A))[B]
print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity = np.zeros(9)
identity = identity.reshape(3,3)
for i in [0,1,2]:
  identity[i,i] = 1

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random = np.random.random((3,3,3))
print(random)

[[[0.96644357 0.07650494 0.22934595]
  [0.78132581 0.21417016 0.79514189]
  [0.85697957 0.5691484  0.32608614]]

 [[0.94363112 0.94744885 0.67752186]
  [0.81271784 0.31671001 0.97490985]
  [0.37011152 0.34290763 0.70093272]]

 [[0.984669   0.43038426 0.5505221 ]
  [0.25039222 0.25010848 0.67148252]
  [0.0532787  0.66843396 0.25383045]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_1 = np.random.random((10,10))
print(random_1)

min = np.min(random_1)
max = np.max(random_1)
print('최솟값:',min, '최댓값:',max)

[[0.06076809 0.84740437 0.51677818 0.73144135 0.90382273 0.03797567
  0.80419188 0.27236994 0.50270085 0.102874  ]
 [0.50076087 0.90524211 0.53204572 0.2377779  0.49153946 0.45968172
  0.3803328  0.58018806 0.19966016 0.39564552]
 [0.8795967  0.83693599 0.45305399 0.83180623 0.2645599  0.23153844
  0.80127265 0.9096215  0.98267682 0.37336775]
 [0.62993861 0.06265234 0.06359122 0.64452397 0.94702065 0.98594004
  0.12381809 0.77257228 0.6569062  0.61212134]
 [0.62839667 0.08752235 0.74387011 0.02105091 0.07983031 0.2285979
  0.87865645 0.19340951 0.0112665  0.43709356]
 [0.80651108 0.37972545 0.02988498 0.07759852 0.3372634  0.76198383
  0.92845317 0.70231046 0.25190325 0.53108787]
 [0.73410417 0.7746596  0.45709048 0.56147753 0.11071779 0.99122358
  0.01396334 0.96277721 0.47299838 0.72872196]
 [0.28798702 0.18663789 0.27798506 0.49914325 0.55490607 0.71141608
  0.39675427 0.09928309 0.73075825 0.33091136]
 [0.28844963 0.59780395 0.46089861 0.63721536 0.80025709 0.8436661
  0.07991244 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_2 = np.random.random(30)
print(random_2)

mean = np.mean(random_2)
print('평균: ', mean)

[0.71781598 0.17400613 0.19185659 0.92300012 0.94847524 0.2914526
 0.03095839 0.49894254 0.57107545 0.26396144 0.75822497 0.07599057
 0.4236901  0.6062274  0.57046225 0.67608553 0.82518409 0.31792581
 0.99192303 0.14285101 0.40476268 0.77041908 0.12951649 0.0452206
 0.79194309 0.4207651  0.54443553 0.39457259 0.46962373 0.84611746]
평균:  0.4939161867606663


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array2d = np.ones(16)
array2d = array2d.reshape(4,4)

array2d[1:-1:,1:-1:]=0
print(array2d)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
mat_2 = np.zeros(25)
mat_2 = mat_2.reshape(5,5)

for i in [0,1,2,3]:
  mat_2[i+1,i] = i+1

print(mat_2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
mat_3 = np.zeros(64)
mat_3 = mat_3.reshape(8,8)
mat_3[::2,1::2] = 1
mat_3[1::2,::2] = 1
print(mat_3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
mat_4 = np.random.random((5,5))
mean_mat = np.mean(mat_4)
var_mat = np.var(mat_4)
Z = (mat_4 - mean_mat)/var_mat
print(Z)

[[ 4.03379823  3.05209561 -2.04639262 -2.58376195 -2.88660834]
 [ 3.15995524 -1.28558012 -1.71484538  0.60057961 -3.90882602]
 [ 4.03598161 -2.91097453  0.99593895 -3.52042681  2.98832622]
 [ 3.99694688  2.020787    1.31081791 -2.86181285 -3.65602818]
 [-3.84594398  3.86482516  3.86074046 -1.94533338 -0.75425873]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
np.dtype([('Red',np.ubyte),('Green',np.ubyte),('Blue',np.ubyte),('Alpha',np.ubyte)])

dtype([('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')])